### PR TITLE
Feature/adds contributing file

### PR DESCRIPTION
**Pull request by ryanwelcher**
### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ryanwelcher** [comment]
@jeffpaul this is the boilerplate as is. Wondering if we should remove the part about `stable` as there is not really a release for this plugin that goes to .org

**Comment by jeffpaul** [comment]
seems reasonable, though will want to update base branch from master to develop now for this PR

**Comment by ryanwelcher** [comment]
done - just need an approval to merge!

**Review by jeffpaul — APPROVED** [review]
all good, thanks!

**Pull request merged**
